FIND_PATH(LIBSHOUT_INCLUDE_DIR shout/shout.h)

FIND_LIBRARY(LIBSHOUT_LIBRARIES NAMES shout)

IF (LIBSHOUT_LIBRARIES AND LIBSHOUT_INCLUDE_DIR)
  SET(LIBSHOUT_FOUND "YES")
ELSE (LIBSHOUT_LIBRARIES AND LIBSHOUT_INCLUDE_DIR)
  SET(LIBSHOUT_FOUND "NO")
ENDIF (LIBSHOUT_LIBRARIES AND LIBSHOUT_INCLUDE_DIR)
 
IF (LIBSHOUT_FOUND)
  IF (NOT LIBSHOUT_FIND_QUIETLY)
    MESSAGE(STATUS "Found LIBSHOUT: ${LIBSHOUT_LIBRARIES}")
  ENDIF (NOT LIBSHOUT_FIND_QUIETLY)
  ELSE (LIBSHOUT_FOUND)
  IF (LIBSHOUT_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find LIBSHOUT library")
  ENDIF (LIBSHOUT_FIND_REQUIRED)
ENDIF (LIBSHOUT_FOUND)
