FIND_PATH(LIBBOOST_DATE_TIME_INCLUDE_DIR boost/date_time/posix_time/posix_time.hpp)

FIND_LIBRARY(LIBBOOST_DATE_TIME_LIBRARIES NAMES boost_date_time)

IF (LIBBOOST_DATE_TIME_LIBRARIES AND LIBBOOST_DATE_TIME_INCLUDE_DIR)
  SET(LIBBOOST_DATE_TIME_FOUND "YES")
ELSE (LIBBOOST_DATE_TIME_LIBRARIES AND LIBBOOST_DATE_TIME_INCLUDE_DIR)
  SET(LIBBOOST_DATE_TIME_FOUND "NO")
ENDIF (LIBBOOST_DATE_TIME_LIBRARIES AND LIBBOOST_DATE_TIME_INCLUDE_DIR)
 
IF (LIBBOOST_DATE_TIME_FOUND)
  IF (NOT LIBBOOST_DATE_TIME_FIND_QUIETLY)
    MESSAGE(STATUS "Found LIBBOOST_DATE_TIME: ${LIBBOOST_DATE_TIME_LIBRARIES}")
  ENDIF (NOT LIBBOOST_DATE_TIME_FIND_QUIETLY)
  ELSE (LIBBOOST_DATE_TIME_FOUND)
  IF (LIBBOOST_DATE_TIME_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find LIBBOOST_DATE_TIME library")
  ENDIF (LIBBOOST_DATE_TIME_FIND_REQUIRED)
ENDIF (LIBBOOST_DATE_TIME_FOUND)
